version: "3"
services:
  mysql_flask:
    container_name: "mysql_flask"
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "flask_framework"
    command: --default-authentication-plugin=mysql_native_password
  app:
    build: . 
    ports:
      - "5000:5000"
    command: bash -c "./wait-for-it.sh -t 0 mysql_flask:3306 -- flask db upgrade && python app.py"
    links:
      - mysql_flask
    depends_on:
      - mysql_flask
